# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."danielnayloruk-reindex" = {
    image = "compose2nix/danielnayloruk-reindex";
    environment = {
      "BASE_FOLDER" = "/home/daniel/Documents/projects/dn410_server/notes";
      "PORT" = "5005";
    };
    volumes = [
      "/home/daniel/Documents/projects/dn410_server:/base_folder:rw"
    ];
    cmd = [ "uv" "run" "python" "index_htmls.py" ];
    dependsOn = [
      "danielnayloruk-search"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=reindex"
      "--network=danielnayloruk_default"
    ];
  };
  systemd.services."docker-danielnayloruk-reindex" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-danielnayloruk_default.service"
    ];
    requires = [
      "docker-network-danielnayloruk_default.service"
    ];
    partOf = [
      "docker-compose-danielnayloruk-root.target"
    ];
    wantedBy = [
      "docker-compose-danielnayloruk-root.target"
    ];
  };
  virtualisation.oci-containers.containers."danielnayloruk-search" = {
    image = "compose2nix/danielnayloruk-search";
    volumes = [
      "/home/daniel/Documents/projects/dn410_server/docker-data/sonic:/usr/src/sonic/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=search"
      "--network=danielnayloruk_default"
    ];
  };
  systemd.services."docker-danielnayloruk-search" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-danielnayloruk_default.service"
    ];
    requires = [
      "docker-network-danielnayloruk_default.service"
    ];
    partOf = [
      "docker-compose-danielnayloruk-root.target"
    ];
    wantedBy = [
      "docker-compose-danielnayloruk-root.target"
    ];
  };
  virtualisation.oci-containers.containers."danielnayloruk-site" = {
    image = "compose2nix/danielnayloruk-site";
    environment = {
      "BASE_FOLDER" = "/home/daniel/Documents/projects/dn410_server/notes";
      "PORT" = "5005";
    };
    volumes = [
      "/home/daniel/Documents/projects/dn410_server:/base_folder:rw"
    ];
    ports = [
      "127.0.0.1:8000/tcp"
    ];
    dependsOn = [
      "danielnayloruk-search"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=site"
      "--network=danielnayloruk_default"
    ];
  };
  systemd.services."docker-danielnayloruk-site" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-danielnayloruk_default.service"
    ];
    requires = [
      "docker-network-danielnayloruk_default.service"
    ];
    partOf = [
      "docker-compose-danielnayloruk-root.target"
    ];
    wantedBy = [
      "docker-compose-danielnayloruk-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-danielnayloruk_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f danielnayloruk_default";
    };
    script = ''
      docker network inspect danielnayloruk_default || docker network create danielnayloruk_default
    '';
    partOf = [ "docker-compose-danielnayloruk-root.target" ];
    wantedBy = [ "docker-compose-danielnayloruk-root.target" ];
  };

  # Builds
  systemd.services."docker-build-danielnayloruk-reindex" = {
    path = [ pkgs.docker pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/daniel/Documents/projects/dn410_server
      docker build -t compose2nix/danielnayloruk-reindex .
    '';
  };
  systemd.services."docker-build-danielnayloruk-search" = {
    path = [ pkgs.docker pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/daniel/Documents/projects/dn410_server/sonic
      docker build -t compose2nix/danielnayloruk-search .
    '';
  };
  systemd.services."docker-build-danielnayloruk-site" = {
    path = [ pkgs.docker pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/daniel/Documents/projects/dn410_server
      docker build -t compose2nix/danielnayloruk-site .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-danielnayloruk-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
